site_name: Globo Recommendation FIAP Docs

theme:
  name: material
  #font: 
  #  text: Merriweather Sans
  #  code: Red Hat Mono
  logo: assets/FIAP_logo.png
  favicon: assets/FIAP_logo.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

plugins:
 - mkdocstrings

markdown_extensions:
 - pymdownx.emoji
 - pymdownx.tasklist
 - pymdownx.mark
 - pymdownx.tilde
 - pymdownx.highlight

nav:
 - Overview: index.md
 - Project: project.md 
 - System architecture : sysarchitecture.md
 - Model: model.md
 - API Documentation: API.md
 - Checklist: checklist.md