name: CI_Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
  
    env:
      BLOB_API_KEY: ${{ secrets.BLOB_API_KEY }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      LAST_NEWS: ${{ secrets.LAST_NEWS }}
      LAST_ACCESS: ${{ secrets.LAST_ACCESS }}
      LAST_ACCESS_PART: ${{ secrets.LAST_ACCESS_PART }}

    steps:
      - name: Copy Repository files from GH to workflow
        uses: actions/checkout@v3
      
      - name: Intall python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: pipx install poetry
      
      - name: Install Dependencies
        run: poetry install
      
      - name: Run Lint and Tests
        run: poetry run task test
