name: CI_Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Repository files from GH to workflow
        uses: actions/checkout@v3
      
      - name: Intall python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: pipx install poetry
      
      - name: Install Dependencies
        run: poetry install
      
      - name: Run Lint and Tests
        run: poetry run task test
