name: CI_Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
  
    env:
      BLOB_API_KEY: ${{ secrets.BLOB_API_KEY }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      LAST_NEWS: ${{ secrets.LAST_NEWS }}
      LAST_ACCESS: ${{ secrets.LAST_ACCESS }}
      LAST_NEWS_RANK: ${{ secrets.LAST_NEWS_RANK }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
      PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
      HOSTNAME_SERVER: ${{ secrets.HOSTNAME_SERVER }}
      DB_CONTAINER_NAME: ${{ secrets.DB_CONTAINER_NAME }}
      PG_CONTAINER_NAME: ${{ secrets.PG_CONTAINER_NAME }}
      APP_CONTAINER_NAME: ${{ secrets.APP_CONTAINER_NAME }}
      PG_PORT: ${{ secrets.PG_PORT }}
      

    steps:
      - name: Copy Repository files from GH to workflow
        uses: actions/checkout@v3
      
      - name: Intall python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: pipx install poetry
      
      - name: Install Dependencies
        run: poetry install
      
      - name: Run Lint and Tests
        run: poetry run task test
